# Define here additional files to process while creating XHTML document
# e.g.
# ADDITIONAL_FILES = Media/foobar
ADDITIONAL_FILES = 

# Source generic Makefile
# IMPORTANT: do not move this line !
#            keep $(ADDITIONAL_FILES) variable declaration above
#            and new targets below it
include ../Scripts/Makefile.generic

# Describe how to process your additional targets, e.g.:
#
# Media/foobar: foobar.src
# 	my_super_script <$^ >$@
